# Generated by Django 3.1.3 on 2021-03-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20210319_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='pics')),
                ('service', models.CharField(max_length=100)),
                ('para', models.CharField(max_length=500)),
            ],
        ),
    ]
