# Generated by Django 3.1.3 on 2021-03-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='title',
        ),
    ]
