# Generated by Django 3.1.3 on 2021-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_auto_20210320_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500000)),
                ('image', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
