# Generated by Django 3.1.3 on 2021-03-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='bimg',
        ),
    ]
