# Generated by Django 3.1.3 on 2021-03-23 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
